"""PyOhNet: definition of ohNet debug levels
"""

kDebugLevel = { 'None':          0,
                'Trace':         1 << 1,
                'Thread':        1 << 2,
                'Network':       1 << 3,
                'Timer':         1 << 4,
                'SsdpMulticast': 1 << 5,
                'SsdpUnicast':   1 << 6,
                'Http':          1 << 7,
                'Device':        1 << 8,
                'XmlFetch':      1 << 9,
                'Service':       1 << 10,
                'Event':         1 << 11,
                'Topology':      1 << 12,
                'DvInvocation':  1 << 13,
                'DvEvent':       1 << 14,
                'DvWebSocket':   1 << 15,
                'Media':         1 << 16,
                'Bonjour':       1 << 17,
                'DvDevice':      1 << 18,
                'Codec':         1 << 19,
                'Error':         1 << 30,
                'All':           0x7FFFFFFF,
                'Verbose':       0x80000000 }
