####################################################################
#
# Makefile for ETSI operators library
# $Id: Makefile,v 1.2 2004-06-24 16:48:01 ehr Exp $
#
####################################################################
include make.cfg


################## user section: insert objlist here #######
LIB = libetsiop.a


OBJS =	$(OBJDIR)/count.o \
	$(OBJDIR)/basicop2.o \
	$(OBJDIR)/oper_32b.o

include stdtargets.cfg

DATE   :=$(shell date +%Y-%m-%d)
TARGET  = libetsiop
