/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_controlpoint_ArgumentString */

#ifndef _Included_org_openhome_net_controlpoint_ArgumentString
#define _Included_org_openhome_net_controlpoint_ArgumentString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_controlpoint_ArgumentString
 * Method:    ActionArgumentCreateStringInput
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_controlpoint_ArgumentString_ActionArgumentCreateStringInput
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_openhome_net_controlpoint_ArgumentString
 * Method:    ActionArgumentCreateStringOutput
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_controlpoint_ArgumentString_ActionArgumentCreateStringOutput
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_controlpoint_ArgumentString
 * Method:    ActionArgumentValueString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openhome_net_controlpoint_ArgumentString_ActionArgumentValueString
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
