/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_controlpoint_ArgumentBool */

#ifndef _Included_org_openhome_net_controlpoint_ArgumentBool
#define _Included_org_openhome_net_controlpoint_ArgumentBool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_controlpoint_ArgumentBool
 * Method:    ActionArgumentCreateBoolInput
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_controlpoint_ArgumentBool_ActionArgumentCreateBoolInput
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openhome_net_controlpoint_ArgumentBool
 * Method:    ActionArgumentCreateBoolOutput
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_controlpoint_ArgumentBool_ActionArgumentCreateBoolOutput
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_controlpoint_ArgumentBool
 * Method:    ActionArgumentValueBool
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openhome_net_controlpoint_ArgumentBool_ActionArgumentValueBool
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
