/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_controlpoint_ArgumentUint */

#ifndef _Included_org_openhome_net_controlpoint_ArgumentUint
#define _Included_org_openhome_net_controlpoint_ArgumentUint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_controlpoint_ArgumentUint
 * Method:    ActionArgumentCreateUintInput
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_controlpoint_ArgumentUint_ActionArgumentCreateUintInput
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openhome_net_controlpoint_ArgumentUint
 * Method:    ActionArgumentCreateUintOutput
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_controlpoint_ArgumentUint_ActionArgumentCreateUintOutput
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_controlpoint_ArgumentUint
 * Method:    ActionArgumentValueUint
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_controlpoint_ArgumentUint_ActionArgumentValueUint
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
