/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_controlpoint_CpDeviceListUpnpServiceType */

#ifndef _Included_org_openhome_net_controlpoint_CpDeviceListUpnpServiceType
#define _Included_org_openhome_net_controlpoint_CpDeviceListUpnpServiceType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_controlpoint_CpDeviceListUpnpServiceType
 * Method:    CpDeviceListCreateUpnpServiceType
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Lorg/openhome/net/controlpoint/CpDeviceList/CpDeviceListInitialised;
 */
JNIEXPORT jobject JNICALL Java_org_openhome_net_controlpoint_CpDeviceListUpnpServiceType_CpDeviceListCreateUpnpServiceType
  (JNIEnv *, jobject, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
