/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_controlpoint_CpDeviceListUpnpUuid */

#ifndef _Included_org_openhome_net_controlpoint_CpDeviceListUpnpUuid
#define _Included_org_openhome_net_controlpoint_CpDeviceListUpnpUuid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_controlpoint_CpDeviceListUpnpUuid
 * Method:    CpDeviceListCreateUpnpUuid
 * Signature: (Ljava/lang/String;)Lorg/openhome/net/controlpoint/CpDeviceList/CpDeviceListInitialised;
 */
JNIEXPORT jobject JNICALL Java_org_openhome_net_controlpoint_CpDeviceListUpnpUuid_CpDeviceListCreateUpnpUuid
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
