/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_controlpoint_CpDeviceListUpnpAll */

#ifndef _Included_org_openhome_net_controlpoint_CpDeviceListUpnpAll
#define _Included_org_openhome_net_controlpoint_CpDeviceListUpnpAll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_controlpoint_CpDeviceListUpnpAll
 * Method:    CpDeviceListCreateUpnpAll
 * Signature: ()Lorg/openhome/net/controlpoint/CpDeviceList/CpDeviceListInitialised;
 */
JNIEXPORT jobject JNICALL Java_org_openhome_net_controlpoint_CpDeviceListUpnpAll_CpDeviceListCreateUpnpAll
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
