/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_controlpoint_CpDeviceList */

#ifndef _Included_org_openhome_net_controlpoint_CpDeviceList
#define _Included_org_openhome_net_controlpoint_CpDeviceList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_controlpoint_CpDeviceList
 * Method:    CpDeviceListDestroy
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_controlpoint_CpDeviceList_CpDeviceListDestroy
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openhome_net_controlpoint_CpDeviceList
 * Method:    CpDeviceListRefresh
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_controlpoint_CpDeviceList_CpDeviceListRefresh
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_openhome_net_controlpoint_CpDeviceList_CpDeviceListInitialised */

#ifndef _Included_org_openhome_net_controlpoint_CpDeviceList_CpDeviceListInitialised
#define _Included_org_openhome_net_controlpoint_CpDeviceList_CpDeviceListInitialised
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
