/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_controlpoint_CpDevice */

#ifndef _Included_org_openhome_net_controlpoint_CpDevice
#define _Included_org_openhome_net_controlpoint_CpDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_controlpoint_CpDevice
 * Method:    CpDeviceCUdn
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openhome_net_controlpoint_CpDevice_CpDeviceCUdn
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_controlpoint_CpDevice
 * Method:    CpDeviceCAddRef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_controlpoint_CpDevice_CpDeviceCAddRef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_controlpoint_CpDevice
 * Method:    CpDeviceCRemoveRef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_controlpoint_CpDevice_CpDeviceCRemoveRef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_controlpoint_CpDevice
 * Method:    CpDeviceCGetAttribute
 * Signature: (JLjava/lang/String;)Lorg/openhome/net/controlpoint/CpAttribute;
 */
JNIEXPORT jobject JNICALL Java_org_openhome_net_controlpoint_CpDevice_CpDeviceCGetAttribute
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
