/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_controlpoint_CpDeviceListUpnpRoot */

#ifndef _Included_org_openhome_net_controlpoint_CpDeviceListUpnpRoot
#define _Included_org_openhome_net_controlpoint_CpDeviceListUpnpRoot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_controlpoint_CpDeviceListUpnpRoot
 * Method:    CpDeviceListCreateUpnpRoot
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_controlpoint_CpDeviceListUpnpRoot_CpDeviceListCreateUpnpRoot
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
