/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_controlpoint_CpDeviceListUpnpDeviceType */

#ifndef _Included_org_openhome_net_controlpoint_CpDeviceListUpnpDeviceType
#define _Included_org_openhome_net_controlpoint_CpDeviceListUpnpDeviceType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_controlpoint_CpDeviceListUpnpDeviceType
 * Method:    CpDeviceListCreateUpnpDeviceType
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Lorg/openhome/net/controlpoint/CpDeviceList/CpDeviceListInitialised;
 */
JNIEXPORT jobject JNICALL Java_org_openhome_net_controlpoint_CpDeviceListUpnpDeviceType_CpDeviceListCreateUpnpDeviceType
  (JNIEnv *, jobject, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
