/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_controlpoint_CpProxy */

#ifndef _Included_org_openhome_net_controlpoint_CpProxy
#define _Included_org_openhome_net_controlpoint_CpProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_controlpoint_CpProxy
 * Method:    CpProxyCreate
 * Signature: (Ljava/lang/String;Ljava/lang/String;IJ)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_controlpoint_CpProxy_CpProxyCreate
  (JNIEnv *, jclass, jstring, jstring, jint, jlong);

/*
 * Class:     org_openhome_net_controlpoint_CpProxy
 * Method:    CpProxyDestroy
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_controlpoint_CpProxy_CpProxyDestroy
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_openhome_net_controlpoint_CpProxy
 * Method:    CpProxyService
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_controlpoint_CpProxy_CpProxyService
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_controlpoint_CpProxy
 * Method:    CpProxySubscribe
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_controlpoint_CpProxy_CpProxySubscribe
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_controlpoint_CpProxy
 * Method:    CpProxyUnsubscribe
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_controlpoint_CpProxy_CpProxyUnsubscribe
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_controlpoint_CpProxy
 * Method:    CpProxySetPropertyChanged
 * Signature: (JLorg/openhome/net/controlpoint/IPropertyChangeListener;)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_controlpoint_CpProxy_CpProxySetPropertyChanged
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openhome_net_controlpoint_CpProxy
 * Method:    CpProxySetPropertyInitialEvent
 * Signature: (JLorg/openhome/net/controlpoint/IPropertyChangeListener;)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_controlpoint_CpProxy_CpProxySetPropertyInitialEvent
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_openhome_net_controlpoint_CpProxy
 * Method:    CpProxyVersion
 * Signature: (J)V
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_controlpoint_CpProxy_CpProxyVersion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_controlpoint_CpProxy
 * Method:    CpProxyPropertyReadLock
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_controlpoint_CpProxy_CpProxyPropertyReadLock
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_controlpoint_CpProxy
 * Method:    CpProxyPropertyReadUnlock
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_controlpoint_CpProxy_CpProxyPropertyReadUnlock
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_controlpoint_CpProxy
 * Method:    CpProxyAddProperty
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_controlpoint_CpProxy_CpProxyAddProperty
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_openhome_net_controlpoint_CpProxy_SubscriptionStatus */

#ifndef _Included_org_openhome_net_controlpoint_CpProxy_SubscriptionStatus
#define _Included_org_openhome_net_controlpoint_CpProxy_SubscriptionStatus
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
