/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_device_DvProvider */

#ifndef _Included_org_openhome_net_device_DvProvider
#define _Included_org_openhome_net_device_DvProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_device_DvProvider
 * Method:    DvProviderCreate
 * Signature: (JLjava/lang/String;Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_device_DvProvider_DvProviderCreate
  (JNIEnv *, jclass, jlong, jstring, jstring, jint);

/*
 * Class:     org_openhome_net_device_DvProvider
 * Method:    DvProviderDestroy
 * Signature: (J[JI)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_device_DvProvider_DvProviderDestroy
  (JNIEnv *, jclass, jlong, jlongArray, jint);

/*
 * Class:     org_openhome_net_device_DvProvider
 * Method:    DvProviderAddAction
 * Signature: (JJLorg/openhome/net/device/IDvInvocationListener;)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_device_DvProvider_DvProviderAddAction
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     org_openhome_net_device_DvProvider
 * Method:    DvProviderPropertiesLock
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_device_DvProvider_DvProviderPropertiesLock
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_device_DvProvider
 * Method:    DvProviderPropertiesUnlock
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_device_DvProvider_DvProviderPropertiesUnlock
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_device_DvProvider
 * Method:    DvProviderAddProperty
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_device_DvProvider_DvProviderAddProperty
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openhome_net_device_DvProvider
 * Method:    DvProviderSetPropertyInt
 * Signature: (JJI)Lorg/openhome/net/device/DvProvider/PropertySetStatus;
 */
JNIEXPORT jobject JNICALL Java_org_openhome_net_device_DvProvider_DvProviderSetPropertyInt
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     org_openhome_net_device_DvProvider
 * Method:    DvProviderSetPropertyUint
 * Signature: (JJJ)Lorg/openhome/net/device/DvProvider/PropertySetStatus;
 */
JNIEXPORT jobject JNICALL Java_org_openhome_net_device_DvProvider_DvProviderSetPropertyUint
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_openhome_net_device_DvProvider
 * Method:    DvProviderSetPropertyBool
 * Signature: (JJI)Lorg/openhome/net/device/DvProvider/PropertySetStatus;
 */
JNIEXPORT jobject JNICALL Java_org_openhome_net_device_DvProvider_DvProviderSetPropertyBool
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     org_openhome_net_device_DvProvider
 * Method:    DvProviderSetPropertyString
 * Signature: (JJLjava/lang/String;)Lorg/openhome/net/device/DvProvider/PropertySetStatus;
 */
JNIEXPORT jobject JNICALL Java_org_openhome_net_device_DvProvider_DvProviderSetPropertyString
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     org_openhome_net_device_DvProvider
 * Method:    DvProviderSetPropertyBinary
 * Signature: (JJ[BI)Lorg/openhome/net/device/DvProvider/PropertySetStatus;
 */
JNIEXPORT jobject JNICALL Java_org_openhome_net_device_DvProvider_DvProviderSetPropertyBinary
  (JNIEnv *, jobject, jlong, jlong, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_openhome_net_device_DvProvider_PropertySetStatus */

#ifndef _Included_org_openhome_net_device_DvProvider_PropertySetStatus
#define _Included_org_openhome_net_device_DvProvider_PropertySetStatus
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
