/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_device_DvServerUpnp */

#ifndef _Included_org_openhome_net_device_DvServerUpnp
#define _Included_org_openhome_net_device_DvServerUpnp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_device_DvServerUpnp
 * Method:    DvServerUpnpCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_device_DvServerUpnp_DvServerUpnpCreate
  (JNIEnv *, jclass);

/*
 * Class:     org_openhome_net_device_DvServerUpnp
 * Method:    DvServerUpnpDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_device_DvServerUpnp_DvServerUpnpDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_device_DvServerUpnp
 * Method:    DvServerUpnpAddDevice
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_device_DvServerUpnp_DvServerUpnpAddDevice
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
