/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_controlpoint_Invocation */

#ifndef _Included_org_openhome_net_controlpoint_Invocation
#define _Included_org_openhome_net_controlpoint_Invocation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_controlpoint_Invocation
 * Method:    CpServiceInvocation
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_controlpoint_Invocation_CpServiceInvocation
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_openhome_net_controlpoint_Invocation
 * Method:    CpInvocationAddInput
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_controlpoint_Invocation_CpInvocationAddInput
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openhome_net_controlpoint_Invocation
 * Method:    CpInvocationAddOutput
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_controlpoint_Invocation_CpInvocationAddOutput
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openhome_net_controlpoint_Invocation
 * Method:    CpInvocationError
 * Signature: (J)Lorg/openhome/net/controlpoint/ProxyError;
 */
JNIEXPORT jobject JNICALL Java_org_openhome_net_controlpoint_Invocation_CpInvocationError
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_controlpoint_Invocation
 * Method:    CpInvocationOutputInt
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_openhome_net_controlpoint_Invocation_CpInvocationOutputInt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openhome_net_controlpoint_Invocation
 * Method:    CpInvocationOutputUint
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_controlpoint_Invocation_CpInvocationOutputUint
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openhome_net_controlpoint_Invocation
 * Method:    CpInvocationOutputBool
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_openhome_net_controlpoint_Invocation_CpInvocationOutputBool
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openhome_net_controlpoint_Invocation
 * Method:    CpInvocationOutputString
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openhome_net_controlpoint_Invocation_CpInvocationOutputString
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openhome_net_controlpoint_Invocation
 * Method:    CpInvocationGetOutputBinary
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_openhome_net_controlpoint_Invocation_CpInvocationGetOutputBinary
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
