/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_core_NetworkAdapter */

#ifndef _Included_org_openhome_net_core_NetworkAdapter
#define _Included_org_openhome_net_core_NetworkAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_core_NetworkAdapter
 * Method:    OhNetNetworkAdapterAddress
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openhome_net_core_NetworkAdapter_OhNetNetworkAdapterAddress
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_core_NetworkAdapter
 * Method:    OhNetNetworkAdapterSubnet
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openhome_net_core_NetworkAdapter_OhNetNetworkAdapterSubnet
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_core_NetworkAdapter
 * Method:    OhNetNetworkAdapterMask
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openhome_net_core_NetworkAdapter_OhNetNetworkAdapterMask
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_core_NetworkAdapter
 * Method:    OhNetNetworkAdapterName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openhome_net_core_NetworkAdapter_OhNetNetworkAdapterName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_core_NetworkAdapter
 * Method:    OhNetNetworkAdapterFullName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openhome_net_core_NetworkAdapter_OhNetNetworkAdapterFullName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_core_NetworkAdapter
 * Method:    OhNetNetworkAdapterRemoveRef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_core_NetworkAdapter_OhNetNetworkAdapterRemoveRef
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
