/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_core_NetworkAdapterList */

#ifndef _Included_org_openhome_net_core_NetworkAdapterList
#define _Included_org_openhome_net_core_NetworkAdapterList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_core_NetworkAdapterList
 * Method:    OhNetSubnetListCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_core_NetworkAdapterList_OhNetSubnetListCreate
  (JNIEnv *, jclass);

/*
 * Class:     org_openhome_net_core_NetworkAdapterList
 * Method:    OhNetSubnetListSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openhome_net_core_NetworkAdapterList_OhNetSubnetListSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_core_NetworkAdapterList
 * Method:    OhNetSubnetAt
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_core_NetworkAdapterList_OhNetSubnetAt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openhome_net_core_NetworkAdapterList
 * Method:    OhNetSubnetListDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_core_NetworkAdapterList_OhNetSubnetListDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
