/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_core_ParameterBool */

#ifndef _Included_org_openhome_net_core_ParameterBool
#define _Included_org_openhome_net_core_ParameterBool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_core_ParameterBool
 * Method:    ServiceParameterCreateBool
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_core_ParameterBool_ServiceParameterCreateBool
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
