/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_core_ParameterBinary */

#ifndef _Included_org_openhome_net_core_ParameterBinary
#define _Included_org_openhome_net_core_ParameterBinary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_core_ParameterBinary
 * Method:    ServiceParameterCreateBinary
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_core_ParameterBinary_ServiceParameterCreateBinary
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
