/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ohnet_Parameter */

#ifndef _Included_ohnet_Parameter
#define _Included_ohnet_Parameter
#ifdef __cplusplus
extern "C" {
#endif
#undef ohnet_Parameter_INT_DEFAULT_MIN
#define ohnet_Parameter_INT_DEFAULT_MIN -2147483648L
#undef ohnet_Parameter_INT_DEFAULT_MAX
#define ohnet_Parameter_INT_DEFAULT_MAX 2147483647L
#undef ohnet_Parameter_INT_DEFAULT_STEP
#define ohnet_Parameter_INT_DEFAULT_STEP 1L
#undef ohnet_Parameter_UINT_DEFAULT_MIN
#define ohnet_Parameter_UINT_DEFAULT_MIN 0i64
#undef ohnet_Parameter_UINT_DEFAULT_MAX
#define ohnet_Parameter_UINT_DEFAULT_MAX 9223372036854775807i64
#undef ohnet_Parameter_UINT_DEFAULT_STEP
#define ohnet_Parameter_UINT_DEFAULT_STEP 1i64
/*
 * Class:     ohnet_Parameter
 * Method:    ServiceParameterCreateInt
 * Signature: (Ljava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_ohnet_Parameter_ServiceParameterCreateInt
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     ohnet_Parameter
 * Method:    ServiceParameterCreateUint
 * Signature: (Ljava/lang/String;JJJ)J
 */
JNIEXPORT jlong JNICALL Java_ohnet_Parameter_ServiceParameterCreateUint
  (JNIEnv *, jobject, jstring, jlong, jlong, jlong);

/*
 * Class:     ohnet_Parameter
 * Method:    ServiceParameterCreateBool
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ohnet_Parameter_ServiceParameterCreateBool
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ohnet_Parameter
 * Method:    ServiceParameterCreateString
 * Signature: (Ljava/lang/String;[Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_ohnet_Parameter_ServiceParameterCreateString
  (JNIEnv *, jobject, jstring, jobjectArray, jint);

/*
 * Class:     ohnet_Parameter
 * Method:    ServiceParameterCreateBinary
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ohnet_Parameter_ServiceParameterCreateBinary
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ohnet_Parameter
 * Method:    ServiceParameterCreateRelated
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_ohnet_Parameter_ServiceParameterCreateRelated
  (JNIEnv *, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
