/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_core_ParameterUint */

#ifndef _Included_org_openhome_net_core_ParameterUint
#define _Included_org_openhome_net_core_ParameterUint
#ifdef __cplusplus
extern "C" {
#endif
#undef org_openhome_net_core_ParameterUint_UINT_DEFAULT_MIN
#define org_openhome_net_core_ParameterUint_UINT_DEFAULT_MIN 0i64
#undef org_openhome_net_core_ParameterUint_UINT_DEFAULT_MAX
#define org_openhome_net_core_ParameterUint_UINT_DEFAULT_MAX 9223372036854775807i64
#undef org_openhome_net_core_ParameterUint_UINT_DEFAULT_STEP
#define org_openhome_net_core_ParameterUint_UINT_DEFAULT_STEP 1i64
/*
 * Class:     org_openhome_net_core_ParameterUint
 * Method:    ServiceParameterCreateUint
 * Signature: (Ljava/lang/String;JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_core_ParameterUint_ServiceParameterCreateUint
  (JNIEnv *, jclass, jstring, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
