/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_core_ParameterInt */

#ifndef _Included_org_openhome_net_core_ParameterInt
#define _Included_org_openhome_net_core_ParameterInt
#ifdef __cplusplus
extern "C" {
#endif
#undef org_openhome_net_core_ParameterInt_INT_DEFAULT_MIN
#define org_openhome_net_core_ParameterInt_INT_DEFAULT_MIN -2147483648L
#undef org_openhome_net_core_ParameterInt_INT_DEFAULT_MAX
#define org_openhome_net_core_ParameterInt_INT_DEFAULT_MAX 2147483647L
#undef org_openhome_net_core_ParameterInt_INT_DEFAULT_STEP
#define org_openhome_net_core_ParameterInt_INT_DEFAULT_STEP 1L
/*
 * Class:     org_openhome_net_core_ParameterInt
 * Method:    ServiceParameterCreateInt
 * Signature: (Ljava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_core_ParameterInt_ServiceParameterCreateInt
  (JNIEnv *, jclass, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
