/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_core_PropertyBool */

#ifndef _Included_org_openhome_net_core_PropertyBool
#define _Included_org_openhome_net_core_PropertyBool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_core_PropertyBool
 * Method:    ServicePropertyCreateBoolCp
 * Signature: (Ljava/lang/String;Lorg/openhome/net/controlpoint/IPropertyChangeListener;)Lorg/openhome/net/core/Property/PropertyInitialised;
 */
JNIEXPORT jobject JNICALL Java_org_openhome_net_core_PropertyBool_ServicePropertyCreateBoolCp
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_openhome_net_core_PropertyBool
 * Method:    ServicePropertyCreateBoolDv
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_core_PropertyBool_ServicePropertyCreateBoolDv
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_core_PropertyBool
 * Method:    ServicePropertyValueBool
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openhome_net_core_PropertyBool_ServicePropertyValueBool
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_core_PropertyBool
 * Method:    ServicePropertySetValueBool
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_openhome_net_core_PropertyBool_ServicePropertySetValueBool
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
