/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_core_Property */

#ifndef _Included_org_openhome_net_core_Property
#define _Included_org_openhome_net_core_Property
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_core_Property
 * Method:    ServicePropertyDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_core_Property_ServicePropertyDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
