/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_device_ResourceWriter */

#ifndef _Included_org_openhome_net_device_ResourceWriter
#define _Included_org_openhome_net_device_ResourceWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_device_ResourceWriter
 * Method:    CallbackWriteResourceBegin
 * Signature: (JJILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_device_ResourceWriter_CallbackWriteResourceBegin
  (JNIEnv *, jclass, jlong, jlong, jint, jstring);

/*
 * Class:     org_openhome_net_device_ResourceWriter
 * Method:    CallbackWriteResource
 * Signature: (JJ[BI)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_device_ResourceWriter_CallbackWriteResource
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint);

/*
 * Class:     org_openhome_net_device_ResourceWriter
 * Method:    CallbackWriteResourceEnd
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_device_ResourceWriter_CallbackWriteResourceEnd
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
