/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_core_SubnetList */

#ifndef _Included_org_openhome_net_core_SubnetList
#define _Included_org_openhome_net_core_SubnetList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_core_SubnetList
 * Method:    OhNetSubnetListCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_core_SubnetList_OhNetSubnetListCreate
  (JNIEnv *, jclass);

/*
 * Class:     org_openhome_net_core_SubnetList
 * Method:    OhNetSubnetListSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_openhome_net_core_SubnetList_OhNetSubnetListSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_core_SubnetList
 * Method:    OhNetSubnetAt
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_core_SubnetList_OhNetSubnetAt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_openhome_net_core_SubnetList
 * Method:    OhNetSubnetListDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_core_SubnetList_OhNetSubnetListDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
