#ifndef HEADER_MULTILINE_MACRO
#define HEADER_MULTILINE_MACRO

/*
 * Header providing wrappers for multiline macros. Intended to suppress
 * "C4127: conditional expression is constant"
 * warnings generated by do {...} while(0) macros.
 */

#define MULTI_LINE_MACRO_BEGIN do {

#define MULTI_LINE_MACRO_END \
    __pragma(warning(push)) \
    __pragma(warning(disable:4127)) \
    } while(0) \
    __pragma(warning(pop))

#endif HEADER_MULTILINE_MACRO
