Import('_default_env')

src = Split("""
    ../../../Upnp/Public/Cs/CpDevice.cs
    ../../../Upnp/Public/Cs/CpDeviceUpnp.cs
    ../../../Upnp/Public/Cs/CpProxy.cs
    ../../../Upnp/Public/Cs/Zapp.cs
    """)

libs = Split("""
    System
    System.Core
    WindowsBase
    """)

_default_env['CLILIBS'] = libs
_default_env['LINKS'] = src 
_default_env['MSBuildTarget'] = _default_env.subst('$build_dir/ZappControl')
_default_env['OutputType'] = 'Library'

msproj = _default_env.MSBuildFileGenerator(_default_env.subst('$build_dir/ZappControl'), src, _default_env)
lib = _default_env.MSBuildLibBuilder(_default_env.subst('$build_dir/ZappControl'), msproj, libs)
libInstall = _default_env.Install('$lib', lib)
Alias('ZappControl', libInstall)
Default('ZappControl')
