//*@@@+++@@@@******************************************************************
//
// Microsoft Windows Media
// Copyright (C) Microsoft Corporation. All rights reserved.
//
//*@@@---@@@@******************************************************************
//
// This file autogenerated by autotemplate perl script.  Do not modify!!
//

// Template arguments
#define bDirectMCLT 0
#define bUseMCLT 0
#define bFlip 1
#define fnArg 0
#define bUseDCT 1
// Template function names
#define auOverlapAddV3tpl auOverlapAddV3DCTFlip
// Define functions to instantiate
#define AU_OVERLAPADDV3
// Include the file with templates
#include "templateincludes.h"
// Undefine functions to instantiate
#undef AU_OVERLAPADDV3
// Undefine template function names
#undef auOverlapAddV3tpl
// Undefine template arguments
#undef bDirectMCLT
#undef bUseMCLT
#undef bFlip
#undef fnArg
#undef bUseDCT

// Template arguments
#define bDirectMCLT 0
#define bUseMCLT 0
#define bFlip 0
#define fnArg 1
#define bUseDCT 1
// Template function names
#define auOverlapAddV3tpl auOverlapAddV3DCTNoFlip
// Define functions to instantiate
#define AU_OVERLAPADDV3
// Include the file with templates
#include "templateincludes.h"
// Undefine functions to instantiate
#undef AU_OVERLAPADDV3
// Undefine template function names
#undef auOverlapAddV3tpl
// Undefine template arguments
#undef bDirectMCLT
#undef bUseMCLT
#undef bFlip
#undef fnArg
#undef bUseDCT

// Template arguments
#define bDirectMCLT 0
#define bUseMCLT 1
#define bFlip 0
#define fnArg 2
#define bUseDCT 0
// Template function names
#define auOverlapAddV3tpl auOverlapAddV3MCLTNoFlip
// Define functions to instantiate
#define AU_OVERLAPADDV3
// Include the file with templates
#include "templateincludes.h"
// Undefine functions to instantiate
#undef AU_OVERLAPADDV3
// Undefine template function names
#undef auOverlapAddV3tpl
// Undefine template arguments
#undef bDirectMCLT
#undef bUseMCLT
#undef bFlip
#undef fnArg
#undef bUseDCT

// Template arguments
#define bDirectMCLT 0
#define bUseMCLT 1
#define bFlip 0
#define fnArg 3
#define bUseDCT 1
// Template function names
#define auOverlapAddV3tpl auOverlapAddV3MCLTHistDirectMCLT
// Define functions to instantiate
#define AU_OVERLAPADDV3
// Include the file with templates
#include "templateincludes.h"
// Undefine functions to instantiate
#undef AU_OVERLAPADDV3
// Undefine template function names
#undef auOverlapAddV3tpl
// Undefine template arguments
#undef bDirectMCLT
#undef bUseMCLT
#undef bFlip
#undef fnArg
#undef bUseDCT

// Template arguments
#define bDirectMCLT 1
#define bUseMCLT 1
#define bFlip 0
#define fnArg 4
#define bUseDCT 1
// Template function names
#define auOverlapAddV3tpl auOverlapAddV3DirectMCLTHistDCTDST
// Define functions to instantiate
#define AU_OVERLAPADDV3
// Include the file with templates
#include "templateincludes.h"
// Undefine functions to instantiate
#undef AU_OVERLAPADDV3
// Undefine template function names
#undef auOverlapAddV3tpl
// Undefine template arguments
#undef bDirectMCLT
#undef bUseMCLT
#undef bFlip
#undef fnArg
#undef bUseDCT

