//*@@@+++@@@@******************************************************************
//
// Microsoft Windows Media
// Copyright (C) Microsoft Corporation. All rights reserved.
//
//*@@@---@@@@******************************************************************
//
// This file autogenerated by autotemplate perl script.  Do not modify!!
//

#if TEMPLATE_INCLUDE_INDX == 1
#include "msaudioprotemplate.c"
#else
#error TEMPLATE_INCLUDE_INDX needs to be defined before including this file!
#endif
