Document: ohnet
Title: Debian ohnet Manual
Author: <insert document author here>
Abstract: This manual describes what ohnet is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ohnet/ohnet.sgml.gz

Format: postscript
Files: /usr/share/doc/ohnet/ohnet.ps.gz

Format: text
Files: /usr/share/doc/ohnet/ohnet.text.gz

Format: HTML
Index: /usr/share/doc/ohnet/html/index.html
Files: /usr/share/doc/ohnet/html/*.html
