/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ohnet_Action */

#ifndef _Included_ohnet_Action
#define _Included_ohnet_Action
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ohnet_Action
 * Method:    ServiceActionCreate
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ohnet_Action_ServiceActionCreate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ohnet_Action
 * Method:    ServiceActionDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ohnet_Action_ServiceActionDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ohnet_Action
 * Method:    ServiceActionAddInputParameter
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ohnet_Action_ServiceActionAddInputParameter
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ohnet_Action
 * Method:    ServiceActionAddOutputParameter
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ohnet_Action_ServiceActionAddOutputParameter
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ohnet_Action
 * Method:    ServiceActionName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ohnet_Action_ServiceActionName
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
