/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_core_Action */

#ifndef _Included_org_openhome_net_core_Action
#define _Included_org_openhome_net_core_Action
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_core_Action
 * Method:    ServiceActionCreate
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_core_Action_ServiceActionCreate
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_openhome_net_core_Action
 * Method:    ServiceActionDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_core_Action_ServiceActionDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openhome_net_core_Action
 * Method:    ServiceActionAddInputParameter
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_core_Action_ServiceActionAddInputParameter
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openhome_net_core_Action
 * Method:    ServiceActionAddOutputParameter
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_openhome_net_core_Action_ServiceActionAddOutputParameter
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_openhome_net_core_Action
 * Method:    ServiceActionName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openhome_net_core_Action_ServiceActionName
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
