/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openhome_net_controlpoint_ArgumentString */

#ifndef _Included_openhome_net_controlpoint_ArgumentString
#define _Included_openhome_net_controlpoint_ArgumentString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     openhome_net_controlpoint_ArgumentString
 * Method:    ActionArgumentCreateStringInput
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_openhome_net_controlpoint_ArgumentString_ActionArgumentCreateStringInput
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     openhome_net_controlpoint_ArgumentString
 * Method:    ActionArgumentCreateStringOutput
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_openhome_net_controlpoint_ArgumentString_ActionArgumentCreateStringOutput
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openhome_net_controlpoint_ArgumentString
 * Method:    ActionArgumentValueString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_openhome_net_controlpoint_ArgumentString_ActionArgumentValueString
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
