/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openhome_net_controlpoint_ArgumentInt */

#ifndef _Included_openhome_net_controlpoint_ArgumentInt
#define _Included_openhome_net_controlpoint_ArgumentInt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     openhome_net_controlpoint_ArgumentInt
 * Method:    ActionArgumentCreateIntInput
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_openhome_net_controlpoint_ArgumentInt_ActionArgumentCreateIntInput
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     openhome_net_controlpoint_ArgumentInt
 * Method:    ActionArgumentCreateIntOutput
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_openhome_net_controlpoint_ArgumentInt_ActionArgumentCreateIntOutput
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openhome_net_controlpoint_ArgumentInt
 * Method:    ActionArgumentValueInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openhome_net_controlpoint_ArgumentInt_ActionArgumentValueInt
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
