/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openhome_net_controlpoint_ArgumentBinary */

#ifndef _Included_openhome_net_controlpoint_ArgumentBinary
#define _Included_openhome_net_controlpoint_ArgumentBinary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     openhome_net_controlpoint_ArgumentBinary
 * Method:    ActionArgumentCreateBinaryInput
 * Signature: (J[BI)J
 */
JNIEXPORT jlong JNICALL Java_openhome_net_controlpoint_ArgumentBinary_ActionArgumentCreateBinaryInput
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     openhome_net_controlpoint_ArgumentBinary
 * Method:    ActionArgumentCreateBinaryOutput
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_openhome_net_controlpoint_ArgumentBinary_ActionArgumentCreateBinaryOutput
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openhome_net_controlpoint_ArgumentBinary
 * Method:    ActionArgumentGetValueBinary
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_openhome_net_controlpoint_ArgumentBinary_ActionArgumentGetValueBinary
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
