/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ohnet_CpDeviceList */

#ifndef _Included_ohnet_CpDeviceList
#define _Included_ohnet_CpDeviceList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ohnet_CpDeviceList
 * Method:    CpDeviceListDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ohnet_CpDeviceList_CpDeviceListDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ohnet_CpDeviceList
 * Method:    CpDeviceListRefresh
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ohnet_CpDeviceList_CpDeviceListRefresh
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ohnet_CpDeviceList
 * Method:    CpDeviceListCreateUpnpAll
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ohnet_CpDeviceList_CpDeviceListCreateUpnpAll
  (JNIEnv *, jobject);

/*
 * Class:     ohnet_CpDeviceList
 * Method:    CpDeviceListCreateUpnpRoot
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ohnet_CpDeviceList_CpDeviceListCreateUpnpRoot
  (JNIEnv *, jobject);

/*
 * Class:     ohnet_CpDeviceList
 * Method:    CpDeviceListCreateUpnpUuid
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ohnet_CpDeviceList_CpDeviceListCreateUpnpUuid
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ohnet_CpDeviceList
 * Method:    CpDeviceListCreateUpnpDeviceType
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_ohnet_CpDeviceList_CpDeviceListCreateUpnpDeviceType
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     ohnet_CpDeviceList
 * Method:    CpDeviceListCreateUpnpServiceType
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_ohnet_CpDeviceList_CpDeviceListCreateUpnpServiceType
  (JNIEnv *, jobject, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
