/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_controlpoint_CpDeviceDv */

#ifndef _Included_org_openhome_net_controlpoint_CpDeviceDv
#define _Included_org_openhome_net_controlpoint_CpDeviceDv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_controlpoint_CpDeviceDv
 * Method:    CpDeviceDvCreate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_controlpoint_CpDeviceDv_CpDeviceDvCreate
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
