/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openhome_net_controlpoint_CpService */

#ifndef _Included_openhome_net_controlpoint_CpService
#define _Included_openhome_net_controlpoint_CpService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     openhome_net_controlpoint_CpService
 * Method:    CpServiceCreate
 * Signature: (Ljava/lang/String;Ljava/lang/String;IJ)J
 */
JNIEXPORT jlong JNICALL Java_openhome_net_controlpoint_CpService_CpServiceCreate
  (JNIEnv *, jobject, jstring, jstring, jint, jlong);

/*
 * Class:     openhome_net_controlpoint_CpService
 * Method:    CpServiceDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_openhome_net_controlpoint_CpService_CpServiceDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openhome_net_controlpoint_CpService
 * Method:    CpServiceInvokeAction
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_openhome_net_controlpoint_CpService_CpServiceInvokeAction
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
