/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openhome_net_core_InitParams */

#ifndef _Included_openhome_net_core_InitParams
#define _Included_openhome_net_core_InitParams
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     openhome_net_core_InitParams
 * Method:    OhNetInitParamsCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_openhome_net_core_InitParams_OhNetInitParamsCreate
  (JNIEnv *, jobject);

/*
 * Class:     openhome_net_core_InitParams
 * Method:    OhNetInitParamsDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_openhome_net_core_InitParams_OhNetInitParamsDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openhome_net_core_InitParams
 * Method:    OhNetInitParamsTcpConnectTimeoutMs
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openhome_net_core_InitParams_OhNetInitParamsTcpConnectTimeoutMs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openhome_net_core_InitParams
 * Method:    OhNetInitParamsMsearchTimeSecs
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openhome_net_core_InitParams_OhNetInitParamsMsearchTimeSecs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openhome_net_core_InitParams
 * Method:    OhNetInitParamsMsearchTtl
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openhome_net_core_InitParams_OhNetInitParamsMsearchTtl
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openhome_net_core_InitParams
 * Method:    OhNetInitParamsNumEventSessionThreads
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openhome_net_core_InitParams_OhNetInitParamsNumEventSessionThreads
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openhome_net_core_InitParams
 * Method:    OhNetInitParamsNumXmlFetcherThreads
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openhome_net_core_InitParams_OhNetInitParamsNumXmlFetcherThreads
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openhome_net_core_InitParams
 * Method:    OhNetInitParamsNumActionInvokerThreads
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openhome_net_core_InitParams_OhNetInitParamsNumActionInvokerThreads
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openhome_net_core_InitParams
 * Method:    OhNetInitParamsNumInvocations
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openhome_net_core_InitParams_OhNetInitParamsNumInvocations
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openhome_net_core_InitParams
 * Method:    OhNetInitParamsNumSubscriberThreads
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openhome_net_core_InitParams_OhNetInitParamsNumSubscriberThreads
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openhome_net_core_InitParams
 * Method:    OhNetInitParamsPendingSubscriptionTimeoutMs
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openhome_net_core_InitParams_OhNetInitParamsPendingSubscriptionTimeoutMs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openhome_net_core_InitParams
 * Method:    OhNetInitParamsDvMaxUpdateTimeSecs
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openhome_net_core_InitParams_OhNetInitParamsDvMaxUpdateTimeSecs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openhome_net_core_InitParams
 * Method:    OhNetInitParamsDvNumServerThreads
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openhome_net_core_InitParams_OhNetInitParamsDvNumServerThreads
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openhome_net_core_InitParams
 * Method:    OhNetInitParamsDvNumPublisherThreads
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openhome_net_core_InitParams_OhNetInitParamsDvNumPublisherThreads
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openhome_net_core_InitParams
 * Method:    OhNetInitParamsDvNumWebSocketThreads
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openhome_net_core_InitParams_OhNetInitParamsDvNumWebSocketThreads
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openhome_net_core_InitParams
 * Method:    OhNetInitParamsDvWebSocketPort
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openhome_net_core_InitParams_OhNetInitParamsDvWebSocketPort
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openhome_net_core_InitParams
 * Method:    OhNetInitParamsDvIsBonjourEnabled
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_openhome_net_core_InitParams_OhNetInitParamsDvIsBonjourEnabled
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
