/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ohnet_NetworkAdapter */

#ifndef _Included_ohnet_NetworkAdapter
#define _Included_ohnet_NetworkAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ohnet_NetworkAdapter
 * Method:    OhNetNetworkAdapterAddress
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ohnet_NetworkAdapter_OhNetNetworkAdapterAddress
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ohnet_NetworkAdapter
 * Method:    OhNetNetworkAdapterSubnet
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ohnet_NetworkAdapter_OhNetNetworkAdapterSubnet
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ohnet_NetworkAdapter
 * Method:    OhNetNetworkAdapterName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ohnet_NetworkAdapter_OhNetNetworkAdapterName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ohnet_NetworkAdapter
 * Method:    OhNetNetworkAdapterFullName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ohnet_NetworkAdapter_OhNetNetworkAdapterFullName
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
