/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ohnet_NetworkAdapterList */

#ifndef _Included_ohnet_NetworkAdapterList
#define _Included_ohnet_NetworkAdapterList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ohnet_NetworkAdapterList
 * Method:    OhNetSubnetListSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ohnet_NetworkAdapterList_OhNetSubnetListSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ohnet_NetworkAdapterList
 * Method:    OhNetSubnetAt
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_ohnet_NetworkAdapterList_OhNetSubnetAt
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
