/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_core_ParameterString */

#ifndef _Included_org_openhome_net_core_ParameterString
#define _Included_org_openhome_net_core_ParameterString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_core_ParameterString
 * Method:    ServiceParameterCreateString
 * Signature: (Ljava/lang/String;[Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_core_ParameterString_ServiceParameterCreateString
  (JNIEnv *, jclass, jstring, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
