/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhome_net_core_ParameterRelated */

#ifndef _Included_org_openhome_net_core_ParameterRelated
#define _Included_org_openhome_net_core_ParameterRelated
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openhome_net_core_ParameterRelated
 * Method:    ServiceParameterCreateRelated
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_openhome_net_core_ParameterRelated_ServiceParameterCreateRelated
  (JNIEnv *, jclass, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
