/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ohnet_Property */

#ifndef _Included_ohnet_Property
#define _Included_ohnet_Property
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ohnet_Property
 * Method:    ServicePropertyDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ohnet_Property_ServicePropertyDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ohnet_Property
 * Method:    ServicePropertyCreateIntCp
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ohnet_Property_ServicePropertyCreateIntCp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ohnet_Property
 * Method:    ServicePropertyCreateIntDv
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ohnet_Property_ServicePropertyCreateIntDv
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ohnet_Property
 * Method:    ServicePropertyCreateUintCp
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ohnet_Property_ServicePropertyCreateUintCp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ohnet_Property
 * Method:    ServicePropertyCreateUintDv
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ohnet_Property_ServicePropertyCreateUintDv
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ohnet_Property
 * Method:    ServicePropertyCreateBoolCp
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ohnet_Property_ServicePropertyCreateBoolCp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ohnet_Property
 * Method:    ServicePropertyCreateBoolDv
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ohnet_Property_ServicePropertyCreateBoolDv
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ohnet_Property
 * Method:    ServicePropertyCreateStringCp
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ohnet_Property_ServicePropertyCreateStringCp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ohnet_Property
 * Method:    ServicePropertyCreateStringDv
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ohnet_Property_ServicePropertyCreateStringDv
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ohnet_Property
 * Method:    ServicePropertyCreateBinaryCp
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ohnet_Property_ServicePropertyCreateBinaryCp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ohnet_Property
 * Method:    ServicePropertyCreateBinaryDv
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ohnet_Property_ServicePropertyCreateBinaryDv
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ohnet_Property
 * Method:    ServicePropertyValueInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ohnet_Property_ServicePropertyValueInt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ohnet_Property
 * Method:    ServicePropertyValueUint
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ohnet_Property_ServicePropertyValueUint
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ohnet_Property
 * Method:    ServicePropertyValueBool
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ohnet_Property_ServicePropertyValueBool
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ohnet_Property
 * Method:    ServicePropertyValueString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ohnet_Property_ServicePropertyValueString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ohnet_Property
 * Method:    ServicePropertyGetValueBinary
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ohnet_Property_ServicePropertyGetValueBinary
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ohnet_Property
 * Method:    ServicePropertySetValueInt
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_ohnet_Property_ServicePropertySetValueInt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ohnet_Property
 * Method:    ServicePropertySetValueUint
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ohnet_Property_ServicePropertySetValueUint
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ohnet_Property
 * Method:    ServicePropertySetValueBool
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ohnet_Property_ServicePropertySetValueBool
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ohnet_Property
 * Method:    ServicePropertySetValueString
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ohnet_Property_ServicePropertySetValueString
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ohnet_Property
 * Method:    ServicePropertySetValueBinary
 * Signature: (J[BJ)I
 */
JNIEXPORT jint JNICALL Java_ohnet_Property_ServicePropertySetValueBinary
  (JNIEnv *, jobject, jlong, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
