Import('_default_env')

src = Split("""
    ../../../Upnp/ControlPoint/Services/Cs/CpLinnCoUkComponent1.cs
    ../../../Upnp/ControlPoint/Services/Cs/CpLinnCoUkConfiguration1.cs
    ../../../Upnp/ControlPoint/Services/Cs/CpLinnCoUkDebug2.cs
    ../../../Upnp/ControlPoint/Services/Cs/CpLinnCoUkDiagnostics1.cs
    ../../../Upnp/ControlPoint/Services/Cs/CpLinnCoUkDs1.cs
    ../../../Upnp/ControlPoint/Services/Cs/CpLinnCoUkInfo1.cs
    ../../../Upnp/ControlPoint/Services/Cs/CpLinnCoUkJukebox1.cs
    ../../../Upnp/ControlPoint/Services/Cs/CpLinnCoUkMediaTime1.cs
    ../../../Upnp/ControlPoint/Services/Cs/CpLinnCoUkPlaylist1.cs
    ../../../Upnp/ControlPoint/Services/Cs/CpLinnCoUkPreamp4.cs
    ../../../Upnp/ControlPoint/Services/Cs/CpLinnCoUkProduct3.cs
    ../../../Upnp/ControlPoint/Services/Cs/CpLinnCoUkProxyManager1.cs
    ../../../Upnp/ControlPoint/Services/Cs/CpLinnCoUkPtest1.cs
    ../../../Upnp/ControlPoint/Services/Cs/CpLinnCoUkRadio1.cs
    ../../../Upnp/ControlPoint/Services/Cs/CpLinnCoUkTime1.cs
    ../../../Upnp/ControlPoint/Services/Cs/CpLinnCoUkUi2.cs
    ../../../Upnp/ControlPoint/Services/Cs/CpLinnCoUkVolkano1.cs
    ../../../Upnp/ControlPoint/Services/Cs/CpUpnpOrgAVTransport1.cs
    ../../../Upnp/ControlPoint/Services/Cs/CpUpnpOrgConnectionManager1.cs
    ../../../Upnp/ControlPoint/Services/Cs/CpUpnpOrgContentDirectory1.cs
    ../../../Upnp/ControlPoint/Services/Cs/CpUpnpOrgRenderingControl1.cs
    """)

_default_env['CLILIBS'] = ['ZappControl']
_default_env['LINKS'] = src 
_default_env['MSBuildTarget'] = _default_env.subst('$build_dir/ZappServices')
_default_env['OutputType'] = 'Library'

msproj = _default_env.MSBuildFileGenerator(_default_env.subst('$build_dir/ZappServices'), src, _default_env)
lib = _default_env.MSBuildLibBuilder(_default_env.subst('$build_dir/ZappServices'), msproj, CLILIBS=['ZappControl']) 
libInstall = _default_env.Install('$lib', lib)
Alias('ZappServices', libInstall)
Default('ZappServices')
