(_default_env, _tool_env) = SConscript('../BuildSystem/Initialise.py')
import os
_default_env.SConsignFile('$sconsign_dir/.sconsign.$hardware-$variant')
_default_env['variant_dir'] += '/' + os.path.split(os.getcwd())[1]
_default_env['lib'] = '$install_dir/lib'
#We need to use msbuild instead of mono so we can specify the PlatformTarget. By default PlatformTarget is AnyCPU which causes problems on 64-bit versions of windows 7/Vista when loading 32-bit C++ Dlls.
_default_env.Append(MSBuildFlags = '/property:PlatformTarget=x86 /property:AllowUnsafeBlocks=true')
_tool_env['variant_dir'] = _default_env['variant_dir']
SConscript('SConscript', variant_dir = _default_env['variant_dir'], duplicate = 0, exports = ['_default_env', '_tool_env'])
